### ISSUE TITLE
Сессии и Авторизация

### ISSUE THREAD

**Issue by ghost** [seven-lights/catalog#2]
Здавствуйте, нужно ли использовать сессии в pyramid в месте c авторизацией? Я так понял (возможно ошибаюсь) что механизм авторизации не требует сессий.
@uralbash

**Comment by uralbash** [comment]
Есть разные способы для AuthTktAuthenticationPolicy не надо, для SessionAuthenticationPolicy надо. 
- API http://docs.pylonsproject.org/projects/pyramid/en/latest/api/authentication.html
- пример https://github.com/mmerickel/pyramid_auth_demo
